version: '3'

services:
  mongodb:
    image: mongo:6.0.2

    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    
  mongo-express:
   image: mongo-express:0.54.0

   restart: always
   depends_on:
     - mongodb
   ports:
     - 8080:8081
   environment: 
     - ME_CONFIG_MONGODB_ADMINUSERNAME=$DB_USERNAME
     - ME_CONFIG_MONGODB_ADMINPASSWORD=$DB_PASSWORD
     - ME_CONFIG_MONGODB_SERVER=$DB_SERVER
  app:
    build: .
    depends_on:
     - mongodb
    ports:
      - 3000:3000
    environment: 
      - DB_HOST=$DB_HOST
